; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-geek]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-geek
framework = arduino
monitor_speed = 115200
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -DBOARD_HAS_PSRAM
